FROM quay.io/singlecellpipelinetest/miniconda3:4.8.2
ADD . /app

RUN apt-get update && apt install autoconf make gcc zlib1g-dev libcurl3-dev libssl-dev g++ samtools -y && rm -rf /var/lib/apt/lists/*
RUN git clone --recursive https://github.com/arq5x/lumpy-sv.git && cd ./lumpy-sv && make && cp bin/* /usr/local/bin/. && cp ./scripts/extractSplitReads_BwaMem /usr/local/bin/.

RUN conda install --file /app/conda_base_requirements.yml

ENV PATH="${PATH}:/opt/conda/envs/lumpy/bin"

RUN pip install git+https://github.com/mondrian-scwgs/mondrian.git@mondrian
RUN pip install -e git+https://github.com/amcpherson/blossomv.git#egg=blossomv
RUN pip install networkx==2.1
RUN conda install -c bioconda svaba
RUN pip install git+https://github.com/mondrian-scwgs/csverve.git@command_line


RUN conda install -c bioconda gridss
RUN cp /app/gridss* /opt/conda/bin/

ENV GRIDSS_JAR=/opt/conda/bin/gridss.jar
