FROM quay.io/singlecellpipelinetest/miniconda3:4.8.2
ADD . /app
RUN conda install --file /app/requirements.yml

RUN pip install git+https://github.com/mondrian-scwgs/mondrian.git@dev
RUN pip install git+https://github.com/mondrian-scwgs/csverve.git@command_line
