FROM quay.io/singlecellpipelinetest/miniconda3:4.8.2
ADD . /app

RUN apt-get update && apt-get install -y libltdl7 parallel && rm -rf /var/lib/apt/lists/*

RUN conda install --file /app/align_requirements.yml

RUN pip install git+https://github.com/mondrian-scwgs/mondrian.git@mondrian
