FROM quay.io/singlecellpipelinetest/miniconda3:4.10.3

ADD . /app
ARG VERSION

RUN rm -rf /opt/conda/lib/python2.7/site-packages/remixt* && \
     apt-get update -y && apt install libc-dev libz-dev build-essential parallel libssl-dev -y && \
     rm -rf /var/lib/apt/lists/* && conda install -c bioconda cython
RUN apt update -y && apt install samtools libbz2-dev -y && rm -rf /var/lib/apt/lists/*


RUN conda install --file /app/requirements.yml
RUN pip install pysam

RUN pip install git+https://github.com/amcpherson/remixt.git@haplotype_infer_refactor
RUN mkdir -p /root/.config/matplotlib && echo "backend : Agg" > /root/.config/matplotlib/matplotlibrc

RUN pip install git+https://github.com/mondrian-scwgs/mondrian_utils.git@$VERSION
RUN pip install git+https://github.com/mondrian-scwgs/csverve.git@v0.3.5 --no-deps
RUN pip install click pyvcf


RUN conda create --name bcftools python=3.11
SHELL ["conda", "run", "-n", "bcftools", "/bin/bash", "-c"]
RUN conda install -c conda-forge openssl
RUN conda install -c bioconda bcftools
SHELL ["conda", "run", "-n", "base", "/bin/bash", "-c"]
ENV PATH="${PATH}:/opt/conda/envs/bcftools/bin"
